[tool.poetry]
name = "rss-llm-digest"
version = "0.1.0"
description = "Project with LangChain and HuggingFace"
authors = ["Alex <cigurd186@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.13,<3.15"
langchain-core = "1.2.13"
langchain-classic = "1.0.1"
langchain-chroma = "1.1.0"
langchain-huggingface = "1.2.1"
langchain-community = "0.4.1"
feedparser = "6.0.12"
aiogram = "3.25.0"
transformers = "5.7.0"
torch = "2.11.0"
accelerate = "1.13.0"
loguru = "0.7.3"
chromadb = "1.5.1"
pyyaml = "6.0.3"
apscheduler = "3.11.2"

[tool.poetry.group.dev.dependencies]
flake8 = "7.3.0"

[tool.poetry.group.evals.dependencies]
langsmith = "0.7.9"
python-dotenv = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"